services:
  db:
    image: postgres:latest
    platform: linux/amd64
    container_name: bd_sat_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bd_sat
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: bd_sat_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db